<link href="<?php echo base_url('assets');?>/palatin/fonts/classy.eot" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/classy.svg" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/classy.ttf" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/classy.woff" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/fontawesome-webfont.eot" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/fontawesome-webfont.svg" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/fontawesome-webfont.ttf" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/fontawesome-webfont.woff" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/fontawesome-webfont.woff2" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/FontAwesome.otf" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/FuturaLT-Book.eot" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/FuturaLT-Book.svg" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/FuturaLT-Book.ttf" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/FuturaLT-Book.woff" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/icomoon.eot" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/icomoon.svg" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/icomoon.ttf" rel="stylesheet">
<link href="<?php echo base_url('assets');?>/palatin/fonts/icomoon.woff" rel="stylesheet">